### ISSUE TITLE
`npm start` failing: path not found.

### ISSUE THREAD

**Issue by dsaw** [herebefrogs/gamejam-boilerplate#6]
after running, `npm install` , executing `npm run` seems to fail with a strange error.
![gamejamboilerplatescreenshot](https://user-images.githubusercontent.com/5353891/131258803-e3b68b85-f315-407c-ae56-ffacf78b5c77.PNG)
the directories (src and dist) are present, so not sure why this is coming up. Even the `browsersync` command seems correct.

**Comment by herebefrogs** [comment]
Hey @dsaw, thanks for your report! The quotes around `src` and `dist` in the `browsersync` command were not necessary, and leading to the construction of an invalid path on Windows. I've pushed a fix. If you pull the main branch, `npm start` should now work.
